# Generated by Django 5.2.4 on 2025-07-27 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0002_category_icon_itemreview_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.URLField(blank=True, null=True),
        ),
    ]
