# Generated by Django 5.2.4 on 2025-07-28 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0003_category_is_approved_alter_category_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemimage',
            name='image',
        ),
        migrations.AddField(
            model_name='itemimage',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
