# Generated by Django 5.2.4 on 2025-07-29 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0004_remove_itemimage_image_itemimage_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
