# Generated by Django 5.2.4 on 2025-07-30 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0008_remove_item_category_item_subcategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemReview',
        ),
    ]
