# Generated by Django 5.2.4 on 2025-07-30 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0010_item_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='title',
            new_name='name',
        ),
    ]
