# Generated by Django 5.2.4 on 2025-10-08 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0011_rename_title_item_name_rename_title_subcategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemimage',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
