# Generated by Django 5.2.4 on 2025-10-09 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0012_alter_itemimage_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
