# Generated by Django 5.2.4 on 2025-10-15 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0013_item_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='availability_status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('RENTED', 'Rented'), ('MAINTENANCE', 'Under Maintenance'), ('UNAVAILABLE', 'Unavailable')], default='AVAILABLE', max_length=20),
        ),
    ]
