# Generated by Django 5.2.4 on 2025-10-15 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0014_alter_item_availability_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='is_available',
        ),
    ]
